import Head from 'next/head';
import Image from 'next/image';
import SearchBar from '../components/SearchBar';
import { useState } from 'react';
import User from '../components/User';

export default function Home() {
  return (
    <div className="bg-white-dark dark:bg-blue-very-dark dark:text-white">
      <Head>
        <title>GitGub User Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-6">
        <header className="flex justify-between ">
          <h1 className="font-bold text-xl">devfinder</h1>
          <div className="flex content-center">
            <p className="mr-4">DARK</p>
            <Image src={'/icon-sun.svg'} height="20px" width="20px" alt="light mode" />
          </div>
        </header>
        <SearchBar />
        <User />
      </main>

      {/* <footer>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
